class AngleSig(object):
	def __init__(self, sigs: str) -> None: ...
	def get_sigs(self) -> str: ...
	def __repr__(self) -> str: ...
class HexGrid(Grid):
	def __init__(self, patterns: list[PatternVariant], max_width: int) -> None: ...
class CollisionOption(object):
	class Dashes(CollisionOption):
		def with_color(self, color: Color) -> CollisionOption.Dashes: ...
		def __init__(self, color: Color) -> None: ...
		@property
		def color(self) -> Color: ...
	def __repr__(self) -> str: ...
	class MatchedDashes(CollisionOption):
		def __init__(self) -> None: ...
	class OverloadedParallel(CollisionOption):
		def with_overload(self, overload: OverloadOptions) -> CollisionOption.OverloadedParallel: ...
		def __init__(self, max_line: int, overload: OverloadOptions) -> None: ...
		@property
		def overload(self) -> OverloadOptions: ...
		@property
		def max_line(self) -> int: ...
		def with_max_line(self, max_line: int) -> CollisionOption.OverloadedParallel: ...
	class ParallelLines(CollisionOption):
		def __init__(self) -> None: ...
class Lines(object):
	class SegmentColors(Lines):
		@property
		def colors(self) -> list[Color]: ...
		def with_colors(self, colors: list[Color]) -> Lines.SegmentColors: ...
		def with_collisions(self, collisions: CollisionOption) -> Lines.SegmentColors: ...
		@property
		def triangles(self) -> Triangle: ...
		def with_triangles(self, triangles: Triangle) -> Lines.SegmentColors: ...
		def __init__(self, colors: list[Color], triangles: Triangle, collisions: CollisionOption) -> None: ...
		@property
		def collisions(self) -> CollisionOption: ...
	class Monocolor(Lines):
		def with_color(self, color: Color) -> Lines.Monocolor: ...
		@property
		def bent(self) -> bool: ...
		@property
		def color(self) -> Color: ...
		def with_bent(self, bent: bool) -> Lines.Monocolor: ...
		def __init__(self, color: Color, bent: bool) -> None: ...
	def __repr__(self) -> str: ...
	class Gradient(Lines):
		def with_bent(self, bent: bool) -> Lines.Gradient: ...
		@property
		def segments_per_color(self) -> int: ...
		def __init__(self, colors: list[Color], segments_per_color: int, bent: bool) -> None: ...
		def with_segments_per_color(self, segments_per_color: int) -> Lines.Gradient: ...
		@property
		def colors(self) -> list[Color]: ...
		@property
		def bent(self) -> bool: ...
		def with_colors(self, colors: list[Color]) -> Lines.Gradient: ...
class EndPoint(object):
	class Match(EndPoint):
		def with_radius(self, radius: float) -> EndPoint.Match: ...
		@property
		def radius(self) -> float: ...
		def __init__(self, radius: float) -> None: ...
	def __repr__(self) -> str: ...
	class Point(EndPoint):
		@property
		def point(self) -> Point: ...
		def __init__(self, point: Point) -> None: ...
		def with_point(self, point: Point) -> EndPoint.Point: ...
	class BorderedMatch(EndPoint):
		@property
		def border(self) -> Marker: ...
		def __init__(self, match_radius: float, border: Marker) -> None: ...
		def with_match_radius(self, match_radius: float) -> EndPoint.BorderedMatch: ...
		def with_border(self, border: Marker) -> EndPoint.BorderedMatch: ...
		@property
		def match_radius(self) -> float: ...
class PatternVariant(object):
	def __init__(self, direction: str, angle_sigs: str, great_spell: None | bool = None) -> None: ...
	@property
	def angle_sigs(self) -> str: ...
	def set_direction(self, direction: str) -> None: ...
	@property
	def direction(self) -> str: ...
	def set_great_spell(self, great_spell: bool) -> None: ...
	def set_angle_sigs(self, angle_sigs: str) -> None: ...
	@property
	def great_spell(self) -> bool: ...
class SquareGrid(Grid):
	def __init__(self, patterns: list[PatternVariant], max_width: int, max_scale: float, x_pad: float, y_pad: float) -> None: ...
class Grid(object):
	def draw_to_file(self, file_name: str, scale: float, options: GridOptions, padding: None | float = None) -> None: ...
	def get_bound_scale(self, bound: tuple[float, float], options: float | GridOptions) -> float: ...
	def draw_png(self, scale: float, options: GridOptions, padding: None | float = None) -> list[int]: ...
class Point(object):
	class None_(Point):
		def __init__(self) -> None: ...
	class Single(Point):
		@property
		def marker(self) -> Marker: ...
		def with_marker(self, marker: Marker) -> Point.Single: ...
		def __init__(self, marker: Marker) -> None: ...
	class Double(Point):
		def with_outer(self, outer: Marker) -> Point.Double: ...
		def with_inner(self, inner: Marker) -> Point.Double: ...
		def __init__(self, inner: Marker, outer: Marker) -> None: ...
		@property
		def inner(self) -> Marker: ...
		@property
		def outer(self) -> Marker: ...
	def __repr__(self) -> str: ...
class Intersections(object):
	class Nothing(Intersections):
		def __init__(self) -> None: ...
	class EndsAndMiddle(Intersections):
		@property
		def end(self) -> EndPoint: ...
		def with_middle(self, middle: Point) -> Intersections.EndsAndMiddle: ...
		@property
		def start(self) -> EndPoint: ...
		def with_start(self, start: EndPoint) -> Intersections.EndsAndMiddle: ...
		def with_end(self, end: EndPoint) -> Intersections.EndsAndMiddle: ...
		@property
		def middle(self) -> Point: ...
		def __init__(self, start: EndPoint, middle: Point, end: EndPoint) -> None: ...
	class UniformPoints(Intersections):
		@property
		def point(self) -> Point: ...
		def with_point(self, point: Point) -> Intersections.UniformPoints: ...
		def __init__(self, point: Point) -> None: ...
	def __repr__(self) -> str: ...
class Marker(object):
	@property
	def radius(self) -> float: ...
	def __repr__(self) -> str: ...
	def __init__(self, color: Color, radius: float) -> None: ...
	def with_radius(self, radius: float) -> Marker: ...
	def with_color(self, color: Color) -> Marker: ...
	@property
	def color(self) -> Color: ...
class GridPatternOptions(object):
	class Uniform(GridPatternOptions):
		def __init__(self, intersections: Intersections, lines: Lines) -> None: ...
		def with_intersections(self, intersections: Intersections) -> GridPatternOptions.Uniform: ...
		@property
		def lines(self) -> Lines: ...
		@property
		def intersections(self) -> Intersections: ...
		def with_lines(self, lines: Lines) -> GridPatternOptions.Uniform: ...
	class Changing(GridPatternOptions):
		def __init__(self, variations: list[tuple[Intersections, Lines]], intros: list[AngleSig], retros: list[AngleSig]) -> None: ...
		@property
		def variations(self) -> list[tuple[Intersections, Lines]]: ...
		@property
		def intros(self) -> list[AngleSig]: ...
		def with_variations(self, variations: list[tuple[Intersections, Lines]]) -> GridPatternOptions.Changing: ...
		def with_intros(self, intros: list[AngleSig]) -> GridPatternOptions.Changing: ...
		def with_retros(self, retros: list[AngleSig]) -> GridPatternOptions.Changing: ...
		@property
		def retros(self) -> list[AngleSig]: ...
	def __repr__(self) -> str: ...
class Color(object):
	def __init__(self, r: int, g: int, b: int, a: int) -> None: ...
	def with_b(self, b: int) -> Color: ...
	def __repr__(self) -> str: ...
	@property
	def r(self) -> int: ...
	@property
	def g(self) -> int: ...
	@property
	def b(self) -> int: ...
	@property
	def a(self) -> int: ...
	def with_r(self, r: int) -> Color: ...
	def with_g(self, g: int) -> Color: ...
	def with_a(self, a: int) -> Color: ...
class OverloadOptions(object):
	class Dashes(OverloadOptions):
		@property
		def color(self) -> Color: ...
		def with_color(self, color: Color) -> OverloadOptions.Dashes: ...
		def __init__(self, color: Color) -> None: ...
	def __repr__(self) -> str: ...
	class LabeledDashes(OverloadOptions):
		@property
		def label(self) -> Marker: ...
		@property
		def color(self) -> Color: ...
		def __init__(self, color: Color, label: Marker) -> None: ...
		def with_color(self, color: Color) -> OverloadOptions.LabeledDashes: ...
		def with_label(self, label: Marker) -> OverloadOptions.LabeledDashes: ...
	class MatchedDashes(OverloadOptions):
		def __init__(self) -> None: ...
class Triangle(object):
	def __repr__(self) -> str: ...
	class BorderMatch(Triangle):
		def __init__(self, match_radius: float, border: Marker) -> None: ...
		@property
		def border(self) -> Marker: ...
		def with_border(self, border: Marker) -> Triangle.BorderMatch: ...
		def with_match_radius(self, match_radius: float) -> Triangle.BorderMatch: ...
		@property
		def match_radius(self) -> float: ...
	class None_(Triangle):
		def __init__(self) -> None: ...
	class Match(Triangle):
		def __init__(self, radius: float) -> None: ...
		@property
		def radius(self) -> float: ...
		def with_radius(self, radius: float) -> Triangle.Match: ...
	class BorderStartMatch(Triangle):
		def __init__(self, match_radius: float, border: Marker) -> None: ...
		def with_border(self, border: Marker) -> Triangle.BorderStartMatch: ...
		def with_match_radius(self, match_radius: float) -> Triangle.BorderStartMatch: ...
		@property
		def border(self) -> Marker: ...
		@property
		def match_radius(self) -> float: ...
class GridOptions(object):
	def with_line_thickness(self, line_thickness: float) -> GridOptions: ...
	def __repr__(self) -> str: ...
	@property
	def pattern_options(self) -> GridPatternOptions: ...
	def __init__(self, line_thickness: float, pattern_options: GridPatternOptions, center_dot: Point) -> None: ...
	@property
	def line_thickness(self) -> float: ...
	def with_center_dot(self, center_dot: Point) -> GridOptions: ...
	def with_pattern_options(self, pattern_options: GridPatternOptions) -> GridOptions: ...
	@property
	def center_dot(self) -> Point: ...