name: Deploy docs

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      #- name: Install Nox
      #  run: uv pip install --system nox

      #- name: Generate docs
      #  timeout-minutes: 5
      #  run: nox --session docs -- build

      - name: Install Dependencies
        run: pip install -e '.[dev]'
      
      - run: cd docs
      - run: ls

      - name: Build Website
        run: make html
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - id: deploy-pages
        uses: actions/deploy-pages@v4